default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: 12345
  pool: 5

development:
  <<: *default
  database: colchonet_development
test:
  <<: *default
  database: colchonet_test

production:
  <<: *default
  database: colchonet_production
