default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: 12345
  pool: 5

development:
  <<: *default
  database: recomendareforco_development
test:
  <<: *default
  database: recomendareforco_test

production:
  <<: *default
  database: recomendareforco_production